### ISSUE TITLE
No module named 'tools.slicer2'

### ISSUE THREAD

**Issue by bayun2016** [AIFSH/GSTTS-ComfyUI#4]
求大佬指点：
Traceback (most recent call last):
  File "E:\dev_tools\ComfyUI-aki-v1.3\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI\__init__.py", line 3, in <module>
    from .tts_node import TextDictNode, GSVTTSNode
  File "E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI\tts_node.py", line 2, in <module>
    from .ft_node import SoVITS_weight_root,GPT_weight_root,\
  File "E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI\ft_node.py", line 18, in <module>
    from tools.slicer2 import Slicer
ModuleNotFoundError: No module named 'tools.slicer2'

Cannot import E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI module for custom nodes: No module named 'tools.slicer2'

**Comment by bayun2016** [comment]
补充下诊断包的信息：
ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

## ComfyUI-Manager: EXECUTE => ['E:\\dev_tools\\ComfyUI-aki-v1.3\\python\\python.exe', '-m', 'pip', 'install', "onnxruntime; sys_platform == 'darwin'"]

## Execute install/(de)activation script for 'E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI'
 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl, https://pypi.oystermercury.top/os
 Ignoring onnxruntime: markers 'sys_platform == "darwin"' don't match your environment

## ComfyUI-Manager: EXECUTE => ['E:\\dev_tools\\ComfyUI-aki-v1.3\\python\\python.exe', '-m', 'pip', 'install', 'g2p_en']

## Execute install/(de)activation script for 'E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI'
 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl, https://pypi.oystermercury.top/os
  
## ComfyUI-Manager: EXECUTE => ['E:\\dev_tools\\ComfyUI-aki-v1.3\\python\\python.exe', '-m', 'pip', 'install', 'PyYAML']

## Execute install/(de)activation script for 'E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI'
 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl, https://pypi.oystermercury.top/os
 
## ComfyUI-Manager: EXECUTE => ['E:\\dev_tools\\ComfyUI-aki-v1.3\\python\\python.exe', '-m', 'pip', 'install', 'jieba_fast']

## Execute install/(de)activation script for 'E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI'
 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl, https://pypi.oystermercury.top/os
 
## ComfyUI-Manager: EXECUTE => ['E:\\dev_tools\\ComfyUI-aki-v1.3\\python\\python.exe', '-m', 'pip', 'install', 'LangSegment>=0.2.0']

## Execute install/(de)activation script for 'E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI'
 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl, https://pypi.oystermercury.top/os
  
## ComfyUI-Manager: EXECUTE => ['E:\\dev_tools\\ComfyUI-aki-v1.3\\python\\python.exe', '-m', 'pip', 'install', 'Faster_Whisper']

## Execute install/(de)activation script for 'E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI'
 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl, https://pypi.oystermercury.top/os
  
## ComfyUI-Manager: EXECUTE => ['E:\\dev_tools\\ComfyUI-aki-v1.3\\python\\python.exe', '-m', 'pip', 'install', 'rotary_embedding_torch']

## Execute install/(de)activation script for 'E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI'
 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl, https://pypi.oystermercury.top/os
  Requirement skipped by policy constraint: torch>=2.0
 
## ComfyUI-Manager: EXECUTE => ['E:\\dev_tools\\ComfyUI-aki-v1.3\\python\\python.exe', '-m', 'pip', 'install', 'ko_pron']

## Execute install/(de)activation script for 'E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI'
 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl, https://pypi.oystermercury.top/os
 
## ComfyUI-Manager: EXECUTE => ['E:\\dev_tools\\ComfyUI-aki-v1.3\\python\\python.exe', '-m', 'pip', 'install', "opencc; sys_platform != 'linux'"]

## Execute install/(de)activation script for 'E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI'
 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl, https://pypi.oystermercury.top/os
 
## ComfyUI-Manager: EXECUTE => ['E:\\dev_tools\\ComfyUI-aki-v1.3\\python\\python.exe', '-m', 'pip', 'install', "opencc==1.1.1; sys_platform == 'linux'"]

## Execute install/(de)activation script for 'E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI'
 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl, https://pypi.oystermercury.top/os
 Ignoring opencc: markers 'sys_platform == "linux"' don't match your environment

## ComfyUI-Manager: EXECUTE => ['E:\\dev_tools\\ComfyUI-aki-v1.3\\python\\python.exe', '-m', 'pip', 'install', "python_mecab_ko; sys_platform != 'win32'"]

## Execute install/(de)activation script for 'E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\GSTTS-ComfyUI'
 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl, https://pypi.oystermercury.top/os
 Ignoring python_mecab_ko: markers 'sys_platform != "win32"' don't match your environment

[ComfyUI-Manager] Startup script completed.

**Comment by bayun2016** [comment]
tools目录中有slicer2.py文件，但是识别不了无法导入
![image](https://github.com/user-attachments/assets/d02fac7b-9ac1-4536-8984-30bd512fdd03)

**Comment by bayun2016** [comment]
已解决

**Comment by hqyaimer** [comment]
咋解决的
